apiVersion: v1
kind: Service
metadata:
  name: helidon-build-publisher-backend
  labels:
    app: helidon-build-publisher-backend
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 9190
    targetPort: 8080
  selector:
    app: helidon-build-publisher-backend
  sessionAffinity: None
