#!/bin/bash -e
#
# Copyright (c) 2020 Oracle and/or its affiliates. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Path to this script
if [ -h "${0}" ] ; then
    readonly SCRIPT_PATH="$(readlink "${0}")"
else
    readonly SCRIPT_PATH="${0}"
fi
readonly SCRIPT_DIR=$(dirname ${SCRIPT_PATH})
readonly SCRIPT=$(basename ${SCRIPT_PATH})
source ${SCRIPT_DIR}/common.sh

usage(){
  cat <<EOF

DESCRIPTION: Authenticate against a docker registry

USAGE:

$(basename ${SCRIPT}) [OPTIONS] --registry-url=URL  --repository=REPOSITORY --SCOPES=SCOPES --output-file=PATH

  --registry-url=URL
          Registry URL. (e.g. https://registry.docker.io/v2)

  --repository=REPOSITORY
          Image repository. (e.g. library/nginx)

  --scopes=SCOPES
          Authentication scopes. (e.g. "pull" or "push,pull")

  --output-file=PATH
          Path to the output file to store the token.

OPTIONS:

EOF
  common_user_password_usage
  common_usage
}

# parse command line args
ARGS=( "${@}" )
for ((i=0;i<${#ARGS[@]};i++))
{
    ARG=${ARGS[${i}]}
    case ${ARG} in
    "--registry-url="*)
        readonly REGISTRY_URL=${ARG#*=}
        ;;
    "--repository="*)
        readonly REPOSITORY=${ARG#*=}
        ;;
    "--scopes="*)
        readonly SCOPES=${ARG#*=}
        ;;
    "--output-file="*)
        readonly OUTPUT_FILE=${ARG#*=}
        ;;
    *)
        common_process_user_password_args || common_process_args
        ;;
  esac
}

if [ -z "${REGISTRY_URL}" ] ; then
    echo "ERROR: --registry-url option is required"
    usage
    exit 1
elif [ -z "${REPOSITORY}" ] ; then
    echo "ERROR: --repository option is required"
    usage
    exit 1
elif [ -z "${SCOPES}" ] ; then
    echo "ERROR: --scopes option is required"
    usage
    exit 1
elif [ -z "${OUTPUT_FILE}" ] ; then
    echo "ERROR: --output-file option is required"
    usage
    exit 1
fi

common_init

touch ${OUTPUT_FILE} || exit 1

# get auth challenge
readonly RESPONSE_HEADERS=$(mktemp -t XXX-headers)
curl -v -L -D ${RESPONSE_HEADERS} "${REGISTRY_URL}" 1> /dev/null
STATUS=$(grep 'HTTP/1.1 ' ${RESPONSE_HEADERS} | tail -1)
if ! [[ ${STATUS} =~ ^HTTP/1.1\ 401 ]] ; then
    echo "ERROR: Unexpected response: ${STATUS}"
    exit 1
fi

# parse challenge header
readonly CHALLENGE_HEADER_PREFIX="Www-Authenticate: bearer "
readonly CHALLENGE_HEADER=$(grep -i "${CHALLENGE_HEADER_PREFIX}" ${RESPONSE_HEADERS})
readonly CHALLENGE_HEADER_VALUE=${CHALLENGE_HEADER:${#CHALLENGE_HEADER_PREFIX}}
IFS=,
readonly CHALLENGE_HEADER_VALUES=(${CHALLENGE_HEADER_VALUE[*]})
for ((i=0;i<${#CHALLENGE_HEADER_VALUES[@]};i++))
{
    ELT=$(trim ${CHALLENGE_HEADER_VALUES[${i}]})
    if [[ "${ELT}" =~ ^realm=.* ]] ; then
        REALM=${ELT:7:$((${#ELT}-8))}
    elif [[ "${ELT}" =~ ^service=.* ]] ; then
        SERVICE=${ELT:9:$((${#ELT}-10))}
    fi
}
if [ -z "${REALM}" ] || [ -z "${SERVICE}" ] ; then
    echo "ERROR: Unable to parse auth challenge header"
    exit 1
fi

# get token
# TODO set offline_token=1 ?
readonly TOKEN_OPTS="service=${SERVICE}&scope=repository:${REPOSITORY}:${SCOPES}"
if [ ! -z "${UNAME}" ] && [ ! -z "${UPASSWD}" ] ; then
    curl -u "${UNAME}:${UPASSWD}" -D ${RESPONSE_HEADERS} "${REALM}?${TOKEN_OPTS}" | jq -r '.token' > ${OUTPUT_FILE}
else
    curl -D ${RESPONSE_HEADERS} "${REALM}?${TOKEN_OPTS}" | jq -r '.token' > ${OUTPUT_FILE}
fi
STATUS=$(grep 'HTTP/1.1 ' ${RESPONSE_HEADERS} | tail -1)
if ! [[ ${STATUS} =~ ^HTTP/1.1\ 200 ]] ; then
    echo "ERROR: Unexpected response: ${STATUS2}"
    exit 1
fi