#!/bin/bash -e
#
# Copyright (c) 2020 Oracle and/or its affiliates. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Path to this script
if [ -h "${0}" ] ; then
    readonly SCRIPT_PATH="$(readlink "${0}")"
else
    readonly SCRIPT_PATH="${0}"
fi
readonly SCRIPT_DIR=$(dirname ${SCRIPT_PATH})
readonly SCRIPT=$(basename ${SCRIPT_PATH})
source ${SCRIPT_DIR}/_common.sh

usage(){
  cat <<EOF

DESCRIPTION: Push an image tar to a remote registry

USAGE:

$(basename ${SCRIPT}) [OPTIONS] --registry-URL=URL --image=PATH

  --registry-url=URL
          Registry URL to push to. (e.g. https://registry.docker.io/v2)

  --name=NAME
          Qualified image name (with namespace).

  --tag=TAG
          Image tag.

  --image=PATH
          Path to the image tar to be pushed.

OPTIONS:

EOF
  common_user_password_usage
  common_usage
}

# parse command line args
ARGS=( "${@}" )
for ((i=0;i<${#ARGS[@]};i++))
{
    ARG=${ARGS[${i}]}
    case ${ARG} in
    "--registry-url="*)
        readonly REGISTRY_URL=${ARG#*=}
        ;;
    "--name="*)
        readonly IMAGE_NAME=${ARG#*=}
        ;;
    "--tag="*)
        readonly IMAGE_TAG=${ARG#*=}
        ;;
    "--image="*)
        readonly IMAGE_TAR=${ARG#*=}
        ;;
    *)
        common_process_user_password_args ${ARG} || common_process_args ${ARG}
        ;;
  esac
}

if [ -z "${IMAGE_TAR}" ] ; then
    echo "ERROR: --image option is required"
    exit 1
elif [ -z "${IMAGE_NAME}" ] ; then
    echo "ERROR: --name option is required"
    exit 1
elif [ -z "${IMAGE_TAG}" ] ; then
    echo "ERROR: --tag option is required"
    exit 1
elif [ ! -f "${IMAGE_TAR}" ] ; then
    echo "ERROR: ${IMAGE_TAR} is not a valid file"
    exit 1
elif [ -z "${REGISTRY_URL}" ] ; then
    echo "ERROR: --registry-url option is required"
    exit 1
fi

common_init

echo "INFO: pushing image..."

readonly API_URL_BASE="${REGISTRY_URL}/${IMAGE_NAME}"
echo "INFO: image_name=${IMAGE_NAME}"
echo "INFO: image_tag=${IMAGE_TAG}"

echo "INFO: authenticating..."
if ${DEBUG} ; then
    AUTH_EXTRA_OPTS="--v"
elif ${DEBUG2} ; then
    AUTH_EXTRA_OPTS="--vv"
fi
if [ ! -z "${STDERR}" ] ; then
    AUTH_EXTRA_OPTS="${AUTH_EXTRA_OPTS} --stderr-file=${STDERR}"
fi
if [ ! -z "${UNAME}" ] && [ ! -z "${UPASSWD}" ] ; then
    AUTH_EXTRA_OPTS="${AUTH_EXTRA_OPTS} --user=${UNAME} --password=${UPASSWD}"
fi
readonly TOKEN_FILE=$(mktemp -t XXX-token})
${SCRIPT_DIR}/auth ${AUTH_EXTRA_OPTS} \
    --registry-url=${REGISTRY_URL} \
    --repository=${IMAGE_NAME} \
    --scopes="push,pull" \
    --output-file=${TOKEN_FILE}

readonly TOKEN=$(cat ${TOKEN_FILE})
readonly AUTH_HEADER="Authorization: Bearer ${TOKEN}"

get_header(){
    grep -i "${1}: " ${2} | awk '{print $2}' | tr -d '\r'
}

get_location() {
    local location=$(get_header "Location" ${1})
    if ! [[ ${location} =~ ^${REGISTRY_URL} ]] ; then
        if [[ ${REGISTRY_URL} =~ /v2$ ]] ; then
            location=${REGISTRY_URL:0:$((${#REGISTRY_URL}-3))}${location}
        else
            location=${REGISTRY_URL}${location}
        fi
    fi
    echo ${location}
}

create_blob(){
    curl -v -X POST \
        -D ${RESPONSE_HEADERS} \
        -H "${AUTH_HEADER}" \
       "${API_URL_BASE}/blobs/uploads/"
    is_http_status_or_die ${RESPONSE_HEADERS} 202
    UPLOAD_LOCATION=$(get_location ${RESPONSE_HEADERS})
}

blob_size(){
    local blobLocation=$(get_location ${RESPONSE_HEADERS})
    curl -v -L --head -H "${AUTH_HEADER}" "${blobLocation}" > ${RESPONSE_HEADERS}
    BLOB_SIZE=$(get_header "Content-Length" ${RESPONSE_HEADERS})
}

readonly IMAGE_MANIFEST="$(mktemp -t XXX}).json"
tar --to-stdout -xf ${IMAGE_TAR} ./manifest.json > ${IMAGE_MANIFEST}
echo "INFO: image_manifest=${IMAGE_MANIFEST}"

readonly IMAGE_CONFIG="$(mktemp -t XXX}).json"
readonly IMAGE_CONFIG_ENTRY=$(jq -r '.[0].Config' ${IMAGE_MANIFEST})
tar --to-stdout -xf ${IMAGE_TAR} ./${IMAGE_CONFIG_ENTRY} > ${IMAGE_CONFIG}
echo "INFO: image_config=${IMAGE_CONFIG}"

readonly IMAGE_CONFIG_DIGEST="sha256:${IMAGE_CONFIG_ENTRY%%.json}"
readonly LAYER_DIGEST=$(jq -r '.rootfs.diff_ids[0]' ${IMAGE_CONFIG})
readonly LAYER_SIZE=$(tar --to-stdout -xf "${IMAGE_TAR}" ./$(jq -r '.[0].Layers[0]' ${IMAGE_MANIFEST}) | wc -c)
echo "INFO: image_config_digest=${IMAGE_CONFIG_DIGEST}"
echo "INFO: layer_digest=${LAYER_DIGEST}"
echo "INFO: layer_size=${LAYER_SIZE}"

RESPONSE_HEADERS=$(mktemp -t XXX})

# upload layer
create_blob
if [[ "${UPLOAD_LOCATION}" =~ \? ]] ; then
    UPLOAD_URL="${UPLOAD_LOCATION}&digest=${LAYER_DIGEST}"
else
    UPLOAD_URL="${UPLOAD_LOCATION}?digest=${LAYER_DIGEST}"
fi
tar --to-stdout -xf "${IMAGE_TAR}" ./$(jq -r '.[0].Layers[0]' ${IMAGE_MANIFEST}) | \
    curl -v -X PUT --data-binary @- \
        -D ${RESPONSE_HEADERS} \
        -H "${AUTH_HEADER}" \
        -H "Content-Type: application/octet-stream" \
        "${UPLOAD_URL}"
is_http_status_or_die ${RESPONSE_HEADERS} 201

# upload image config
create_blob
if [[ "${UPLOAD_LOCATION}" =~ \? ]] ; then
    UPLOAD_URL="${UPLOAD_LOCATION}&digest=${IMAGE_CONFIG_DIGEST}"
else
    UPLOAD_URL="${UPLOAD_LOCATION}?digest=${IMAGE_CONFIG_DIGEST}"
fi
curl -v -X PUT --data-binary @${IMAGE_CONFIG} \
    -D ${RESPONSE_HEADERS} \
    -H "${AUTH_HEADER}" \
    -H "Content-Type: application/vnd.docker.container.image.v1+json" \
    "${UPLOAD_URL}"
is_http_status_or_die ${RESPONSE_HEADERS} 201

blob_size
readonly CONFIG_SIZE=${BLOB_SIZE}
echo "INFO: config_size=${CONFIG_SIZE}"

readonly NUM_LAYERS=$(jq -r '.[0].Layers|length' ${IMAGE_MANIFEST})
readonly REMAINING_LAYERS=( )
for ((i=1;i<${NUM_LAYERS};i++))
{
    REMAINING_LAYERS[{${i}]=$(jq -r ".[0].Layers[${i}]" ${IMAGE_MANIFEST})
}

echo ${REMAINING_LAYERS[*]}

# create distribution manifest
readonly DISTRIBUTION_MANIFEST="$(mktemp -t XXX}).json"
echo "INFO: distribution_manifest=${DISTRIBUTION_MANIFEST}"
cat << EOF > ${DISTRIBUTION_MANIFEST}
{
    "schemaVersion": 2,
    "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
    "config": {
        "mediaType": "application/vnd.docker.container.image.v1+json",
        "size": ${CONFIG_SIZE},
        "digest": "${IMAGE_CONFIG_DIGEST}"
    },
    "layers": [
        {
            "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
            "size": ${LAYER_SIZE},
            "digest": "${LAYER_DIGEST}"
        }
$(for ((i=0;i<${#REMAINING_LAYERS[@]};i++))
{
    if [ "${i}" = "0" ] ; then printf "        ,\n" ; fi
    printf "        {\n"
    printf "        \"mediaType\": \"application/vnd.docker.container.image.v1+json\",\n"
    printf "        \"size\": %i,\n" $(tar --to-stdout -xf "${IMAGE_TAR}" ./${REMAINING_LAYERS[${i}]} | wc -c)
    printf "        \"digest\": \"%s\"" $(dirname ${REMAINING_LAYERS[${i}]})
    printf "        }\n"
    if [ "${i}" = "$((${#LAYERS[@]}-1))" ] ; then printf "\n" ; else printf ",\n" ; fi
})
    ]
}
EOF

# upload manifest
curl -v -X PUT --data-binary @${DISTRIBUTION_MANIFEST} \
    -H "${AUTH_HEADER}" \
    -D ${RESPONSE_HEADERS} \
    -H "Content-Type: application/vnd.docker.distribution.manifest.v2+json" \
    "${API_URL_BASE}/manifests/${IMAGE_TAG}"
is_http_status_or_die ${RESPONSE_HEADERS} 201

echo "INFO: image push completed"