apiVersion: apps/v1
kind: Deployment
metadata:
  name: helidon-build-publisher-backend
  labels:
    app: helidon-build-publisher-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helidon-build-publisher-backend
  template:
    metadata:
      labels:
        app: helidon-build-publisher-backend
    spec:
      restartPolicy: Always
      containers:
      - image: helidon-build-publisher-backend:latest
        imagePullPolicy: IfNotPresent
        name: backend
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /ready
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 20
          timeoutSeconds: 3
          failureThreshold: 10
        livenessProbe:
          httpGet:
            path: /live
            port: 8081
          initialDelaySeconds: 3
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        env:
        - name: storage.path
          value: "/storage"
        - name: http-signature.public-key
          value: "/etc/backend-secret/backend.pem.pub"
        volumeMounts:
        - name: build-publisher-storage
          mountPath: "/storage"
        - name: build-publisher-secret
          mountPath: "/etc/backend-secret"
          readOnly: true
      volumes:
      - name: build-publisher-storage
        persistentVolumeClaim:
          claimName: build-publisher-storage
      - name: build-publisher-secret
        secret:
          secretName: helidon-build-publisher-secret

---

apiVersion: v1
kind: Service
metadata:
  name: helidon-build-publisher-backend
  labels:
    app: helidon-build-publisher-backend
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 9190
    targetPort: 8080
  selector:
    app: helidon-build-publisher-backend
  sessionAffinity: None