apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata: 
  name: "build-publisher-storage"
spec:
  storageClassName: "nfs"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
