apiVersion: v1
kind: Service
metadata:
  name: build-publisher-frontend
  labels:
    app: build-publisher-frontend
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 9292
  selector:
    app: build-publisher-frontend
  sessionAffinity: None
